name: Deploy infrastructure

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "main"
    paths:
      - "infrastructure/**"
    types:
      - closed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  deploy:
    # This job should only run if the PR has been merged
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_CONTROLPLANE }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - uses: azure/setup-kubectl@v4

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy manifests
        run: |
          kubectl apply -f ./infrastructure/
