name: Create and publish frontend Docker image

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "infrastructure/**"
    types:
      - closed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  deploy:
    # This job should only run if the PR has been merged
    if: github.event.pull_request.merged == true

    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_CONTROLPLANE }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            infrastructure/deployment.yaml
            infrastructure/ingress.yaml
            infrastructure/namespace.yaml
            infrastructure/service.yaml
